### ISSUE TITLE
can you elaborate the readme

### ISSUE THREAD

**Issue by dharmendrakariya** [gokulapap/whatsasena-plugins#1]
can you tell in detailed guide how to use the plugin and the security risks in using that

also I want to cant I just use any provider to host the app

**Comment by gokulapap** [comment]
You can use heroku to host the apps, go and visit whatsasena repo and there is a video also in youtube you can watch that and deploy the whatsasena bot in heroku and just install my plugins with [.install] command .

some files are twilio bots

**Comment by dharmendrakariya** [comment]
Thanks @gokulapap
